# Bazel WORKSPACE file for rep+ Android app

workspace(name = "rep_plus")

# Android SDK
android_sdk_repository(
    name = "androidsdk",
    api_level = 33,
)

# Android NDK (optional, if needed for native code)
# android_ndk_repository(
#     name = "androidndk",
#     api_level = 21,
# )

# Kotlin rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_KOTLIN_VERSION = "1.9.0"
RULES_KOTLIN_SHA = "5766f1e599acf551aa56f49dab9ab9108269b03c557496c54acaf41f98e2b8d6"

http_archive(
    name = "rules_kotlin",
    sha256 = RULES_KOTLIN_SHA,
    urls = [
        "https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin-v%s.tar.gz" % (RULES_KOTLIN_VERSION, RULES_KOTLIN_VERSION),
    ],
)

load("@rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories()

load("@rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()
